/** Which components actually hold a reference, and which only have a wish.
 *
 * Two coverage numbers exist in this vault and they measure different things, which is how they
 * started disagreeing in prose:
 *
 *   - `vault/map.py` joins **files** — a ranked, eye-marked moving file whose subject resembles the
 *     component. A component can have eleven files and no measurement taken from any of them.
 *   - `vault/SPECS-FOR.json` records that a **spec was read off a verified file and quoted against
 *     the component** — the thing step 3 of the goal actually asks for.
 *
 * Only the second one makes a component buildable against a reference, so it is the number quoted
 * as coverage. This prints all three tiers and names every component that has no reference at all,
 * because "34 components lack references" is not a work list and a named list is.
 *
 *   node vault/coverage.mjs          # writes vault/COVERAGE.md and prints the one-line truth
 *   node vault/coverage.mjs --check  # exits 1 if the tiers stop adding up to the registry
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

import { COMPONENT_KEYS } from '../app/src/registry/index.js';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const SPECS_FOR = JSON.parse(readFileSync(join(HERE, 'SPECS-FOR.json'), 'utf8'));
const MAPPING = readFileSync(join(HERE, 'MAPPING.md'), 'utf8');

/** Files held per component, read out of the table `map.py` generates. */
function filesHeld () {
  const held = new Map();
  for (const line of MAPPING.split('\n')) {
    const m = line.match(/^\|\s*`([A-Za-z][A-Za-z0-9]*)`\s*\|([^|]*)\|[^|]*\|\s*(\d+)\s*\|/);
    if (m) held.set(m[1], { seed: m[2].trim(), files: Number(m[3]) });
  }
  return held;
}

/** Components quoted in SPECS-FOR, restricted to names the registry can render. */
function specQuoted () {
  const registry = new Set(COMPONENT_KEYS);
  const quoted = new Map();
  for (const [file, entry] of Object.entries(SPECS_FOR)) {
    if (file === '_about') continue;
    for (const name of entry.for || []) {
      if (!registry.has(name)) continue;
      if (!quoted.has(name)) quoted.set(name, []);
      quoted.get(name).push(file);
    }
  }
  return quoted;
}

export function coverage () {
  const files = filesHeld();
  const quoted = specQuoted();
  const tiers = { spec: [], filesOnly: [], none: [] };
  for (const key of COMPONENT_KEYS) {
    if (quoted.has(key)) tiers.spec.push({ key, files: quoted.get(key) });
    else if ((files.get(key) || {}).files > 0) tiers.filesOnly.push({ key, files: (files.get(key)).files, seed: (files.get(key)).seed });
    else tiers.none.push(key);
  }
  return { tiers, total: COMPONENT_KEYS.length, files, quoted };
}

const { tiers, total } = coverage();

if (process.argv.slice(2).includes('--check')) {
  const sum = tiers.spec.length + tiers.filesOnly.length + tiers.none.length;
  if (sum !== total) {
    console.error(`coverage tiers sum to ${sum}, the registry renders ${total} — a component is counted twice or not at all`);
    process.exit(1);
  }
  if (!tiers.spec.length) { console.error('no component is quoted in SPECS-FOR; coverage is zero'); process.exit(1); }
  console.log(`coverage tiers add up: ${tiers.spec.length} spec-held + ${tiers.filesOnly.length} files only + ${tiers.none.length} with nothing = ${total}`);
  process.exit(0);
}

const lines = [
  '# Reference coverage, by tier',
  '',
  `Generated by \`vault/coverage.mjs\`. The registry renders **${total}** components.`,
  '',
  '| tier | meaning | count |',
  '| --- | --- | --- |',
  `| spec-held | a verified file's measurement is quoted against it in \`SPECS-FOR.json\` — buildable against a reference | ${tiers.spec.length} |`,
  `| files only | ranked, eye-marked files resemble it, but no measurement has been read off them | ${tiers.filesOnly.length} |`,
  `| nothing | neither | ${tiers.none.length} |`,
  '',
  'These are not interchangeable. A component with eleven files and no spec row has nobody to copy;',
  'the number quoted as coverage in prose is the spec-held tier, and nothing else.',
  '',
  `## Spec-held (${tiers.spec.length})`,
  '',
  ...tiers.spec.map((r) => `- \`${r.key}\` ← ${r.files.map((f) => `\`${f}\``).join(', ')}`),
  '',
  `## Files only — a picture held, no measurement read (${tiers.filesOnly.length})`,
  '',
  ...tiers.filesOnly.map((r) => `- \`${r.key}\` — ${r.files} file(s), seed \`${r.seed}\``),
  '',
  `## Nothing at all (${tiers.none.length})`,
  '',
  ...tiers.none.map((k) => `- \`${k}\``),
  '',
];
writeFileSync(join(HERE, 'COVERAGE.md'), lines.join('\n'));
console.log(`${tiers.spec.length} of ${total} spec-held · ${tiers.filesOnly.length} files only · ${tiers.none.length} with nothing — COVERAGE.md`);
